spring:
  application:
    name: webfrontboot
  config:
    import: optional:configserver:${CONFIG_SERVER_URL:http://192.168.1.67:8888/}
  web:
    resources:
      static-locations: classpath:/assets/
