apiVersion: v1
kind: Service
metadata:
  name: flights-service-service
  labels:
    app: koratosun-airlines 
spec:
  ports:
    - port: 8092
      targetPort: 8092
  selector:
      app: koratosun-airlines
      tier: microservices
     