apiVersion: apps/v1
kind: Deployment
metadata:
  name: customers-service
spec:
  selector:
    matchLabels:
      app: koratosun-airlines
      tier: microservices
  replicas: 1
  template:
    metadata:
      labels:
        app: koratosun-airlines
        tier: microservices
    spec:
      containers:
      - image: marinoqj/kair-customers:1.0.0
        imagePullPolicy: Always
        name: customers-service
        ports:
        - containerPort: 8091
          protocol: TCP



