spring:
  application:
    name: customers-service
  config:
    import: optional:configserver:${CONFIG_SERVER_URL:http://localhost:8888/}
  kafka:    
    consumer:
      bootstrap-servers: 192.168.2.109:9092
      enable-auto-commit: true
      group-id: kortosunairlines
      auto-offset-reset: earliest									
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: '*'
          deserializer:
            value:
              default:
                type: es.koratosun.airlines.apigateway.domain.Customer							
topic: customers

#logging:
#  level:
#    org.springframework.cloud: DEBUG
